name: nasooh
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  lottie: ^3.0.0
  http: ^0.13.5
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  connectivity_plus: ^5.0.2
  responsive_framework: ^0.2.0
  intl:
  flutter_spinkit: ^5.2.0
  intl_phone_field: ^3.2.0
  password_text_field: ^2.0.0
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.2.17
  smooth_page_indicator: ^1.1.0
  pinput: ^4.0.0
  readmore: ^2.2.0
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  flutter_countdown_timer:
  image_picker:
  file_picker: ^6.1.1
  get: ^4.6.6
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^16.3.2
  firebase_core: ^2.25.4
  url_launcher:
  flutter_rating_bar: ^4.0.1
  audioplayers:
  record:
  permission_handler:
  path_provider:
  uuid:
  myfatoorah_flutter: ^3.0.8
  open_filex: ^4.4.0
  flutter_document_picker: ^5.2.3

dev_dependencies:
  delete_un_used_assets: ^1.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/PNG/mansou7_icon.png"

flutter_native_splash:
  image: assets/images/PNG/NasohSplash.png
  background_image: assets/images/PNG/SplashScreenBackGround.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/SVGs/
    - assets/images/PNG/
    - assets/language/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf