name: nasooh
description: A new Flutter project.
version: 1.0.0+5

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  lottie: ^3.1.0
  http:
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  responsive_framework: ^1.4.0
  intl_phone_field: ^3.2.0
  uuid:
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  pinput: ^4.0.0
  readmore: ^2.2.0
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  flutter_countdown_timer:
  image_picker:
  file_picker: ^8.0.0+1
  get: ^4.6.6
  firebase_messaging:
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.28.0
  url_launcher:
  flutter_rating_bar: ^4.0.1
  audioplayers:
  record:
  permission_handler:
  path_provider:
  myfatoorah_flutter:
  flutter_linkify: ^6.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  delete_un_used_assets: ^1.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/PNG/mansou7_icon.png"

flutter_native_splash:
  image: assets/images/PNG/NasohSplash.png
  background_image: assets/images/PNG/SplashScreenBackGround.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/SVGs/
    - assets/images/PNG/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf